# Generated by Django 4.2.16 on 2024-10-04 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='api.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='api.kid')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.week')),
            ],
        ),
        migrations.CreateModel(
            name='KidVoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='voice/')),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('feedback_state', models.BooleanField(default=False)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='api.week')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('note', models.TextField()),
                ('voice_recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.kidvoicerecording')),
            ],
        ),
    ]
