# Generated by Django 4.2.16 on 2024-10-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidvoicerecording',
            name='media_type',
            field=models.CharField(choices=[('pictures', 'Pictures'), ('video', 'Video')], default='pictures', max_length=10),
        ),
    ]
